(function(){
    window.IBQuestions = [
		"Do you have any phobias?",
		"If you are in a bad mood, do you prefer to be left alone or have someone to cheer you up?",
		"If you could speak to anyone in heaven, who would it be?",
		"What is a relationship deal breaker for you?",
		"What’s the one thing that people always misunderstand about you?",
		"What memory do you replay the most in your mind?",
		"would you rather: go to a photo booth or take silly selfies",
		"If you had a Death Note, would you use it?",
		"How important is physical attraction to you?",
		"At what age did you learn the most about yourself?",
		"When was the last time you were disappointed in yourself?",
		"Is there someone that you’ll never forgive?",
		"Do you think your parents are proud of where you are in life?",
		"What’s the worst physical pain that you’ve ever suffered through?",
		"What’s the most intimate thing a couple could do together?",
		"Do you believe in ghosts, aliens, or any mythical creatures?",
		"Who is that one person you can talk to about just anything?",
		"would you rather: Kiss on the cheek or kiss on the forehead?",
		"When do you feel the most attractive?",
		"What unanswerable question bothers you the most?",
		"At what age did you start to consider yourself an adult?",
		"What is the meanest thing your inner voice tells you?",
		"Do you consider yourself an introvert or an extrovert?",
		"Were you ever tempted to cheat on a past partner?",
		"Are you more into looks or brains?",
		"What do you do when you’re feeling lonely?",
		"What type of animal would you like to be reincarnated as?",
		"Do you believe every life has an equal value?",
		"Do you sleep in pajamas, undies or naked?",
		"would you rather: Have a snowball fight or water ballon fight?",
		"Do you daydream more about the future or your past?",
		"Have you ever been in love before?",
		"What would instantly make you fall out of love with someone?",
		"Do you believe you’re going to be a good parent?",
		"What would you do if your parents didn’t like your partner?",
		"Do you like the sound of your name?",
		"How long did it take you to learn to love yourself?",
		"Have you ever manipulated someone to get what you wanted?",
		"Do you believe in love at first sight or do you think it takes time to grow?",
		"Do you believe in destiny?",

    ];
})();
