(function(){
    window.IBQuestions = [
		"Do you have any phobias?",
		"If you are in a bad mood, do you prefer to be left alone or have someone to cheer you up?",
		"If you could speak to anyone in heaven, who would it be?",
		"What is a relationship deal breaker for you?",
		"What’s the one thing that people always misunderstand about you?",
		"What memory do you replay the most in your mind?",
		"would you rather: go to a photo booth or take silly selfies",
		"If you had a Death Note, would you use it?",
		"How important is physical attraction to you?",
		"At what age did you learn the most about yourself?",
		"When was the last time you were disappointed in yourself?",
		"Is there someone that you’ll never forgive?",
		"Do you think your parents are proud of where you are in life?",
		"What’s the worst physical pain that you’ve ever suffered through?",
		"What’s the most intimate thing a couple could do together?",
		"Do you believe in ghosts, aliens, or any mythical creatures?",
		"Who is that one person you can talk to about just anything?",
		"would you rather: Kiss on the cheek or kiss on the forehead?",
		"When do you feel the most attractive?",
		"What unanswerable question bothers you the most?",
		"At what age did you start to consider yourself an adult?",
		"What is the meanest thing your inner voice tells you?",
		"Do you consider yourself an introvert or an extrovert?",
		"Were you ever tempted to cheat on a past partner?",
		"Are you more into looks or brains?",
		"What do you do when you’re feeling lonely?",
		"What type of animal would you like to be reincarnated as?",
		"Do you believe every life has an equal value?",
		"Do you sleep in pajamas, undies or naked?",
		"would you rather: Have a snowball fight or water ballon fight?",
		"Do you daydream more about the future or your past?",
		"Have you ever been in love before?",
		"What would instantly make you fall out of love with someone?",
		"Do you believe you’re going to be a good parent?",
		"What would you do if your parents didn’t like your partner?",
		"Do you like the sound of your name?",
		"How long did it take you to learn to love yourself?",
		"Have you ever manipulated someone to get what you wanted?",
		"Do you believe in love at first sight or do you think it takes time to grow?",
		"Do you believe in destiny?",
		"What thoughts make you unhappy?",
		"What’s the most childish thing you still love to do?",
		"Before making a telephone call, do you ever rehearse what you are going to say? Why?",
		"What would constitute a “perfect” day for you?",
		"When did you last sing to yourself? To someone else?",
		"Do you have a secret hunch about how you will die?",
		"Name three things you and your game partner appear to have in common.",
		"For what in your life do you feel most grateful?",
		"If you could change anything about the way you were raised, what would it be?",
		"Take four minutes and tell your gaming-partner your life story in as much detail as possible.",
		"If a crystal ball could tell you the truth about yourself, your life, the future or anything else, what would you want to know?",
		"What is the greatest accomplishment of your life?",
		"What do you value most in a friendship?",
		"would you rather: Kiss on the first date or wait a few dates?",
		"What role does physical attraction play in whether or not you pursue a relationship?",
		"What is your most treasured memory?",
		"What is your most terrible memory?",
		"Do you like rough sex or smooth sex?",
		"What is the first thing you noticed about the other players when you first met them?",
		"Have you ever been caught masturbating?",
		"What did your past relationship teach you?",
		"If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?",
		"What does friendship mean to you?",
		"What roles do love and affection play in your life?",
		"Alternate sharing something you consider a positive characteristic of your gaming partner. Share a total of 3 items.",
		"How close and warm is your family? Do you feel your childhood was happier than most other people’s?",
		"How do you feel about your relationship with your mother?",
		"Make three true “we” statements each. For instance, “We are both in this room feeling ... ",
		"If you had to go a week without your phone, what would you miss the most about it?",
		"would you rather: Text people or talk to them in person?",
		"Complete this sentence: “I wish I had someone with whom I could share ... ",
		"If you could have three wishes from your game partner, what would they be?",
		"If you were going to become a close friend with your Game partner, please share what would be important for him or her to know.",
		"When was the last time you broke someone’s heart?",
		"Tell your partner what you like about them.",
		"Share with your partner an embarrassing moment in your life.",
		"When did you last cry in front of another person? By yourself?",
		"What, if anything, is too serious to be joked about?",
		"Your house, containing everything you own, catches fire. After saving your loved ones and pets, you have time to safely make a final dash to save any one item. What would it be? Why?",
		"Of all the people in your family, whose death would you find most disturbing? Why?",
		"How do you feel about the merits of pornography?",
		"What’s the one thing you would like to change about yourself?",
		"What’s the dirtiest thought you’ve ever had about a total stranger?",
		"Do you believe success comes in the form of money or happiness?",
		"What’s the dirtiest fantasy you’ve had at work?",
		"What do you think is your best physical feature?",
		"What do you do when you get horny in public?",
		"What was the best phase in your life?",
		"Do you remember what that first orgasm felt like?",
		"What scares you the most about growing old?",
		"Have you ever had sex with someone whose name you never knew?",
		"Have you ever kissed someone of the same sex?",
		"Do you have any reoccurring dreams or nightmares?",		
		"How would you respond if a couple approached you to be their “third”?",
		"What types of compliments do you like to hear?",
		"Is there anything you won’t do in bed?",
		"How old were you when you lost your virginity?",
		"Do you feel like anything is missing from your life?",
		"Would you rather die a virgin or a whore?",
		"Would you rather: Have amazing sex that lasts 47 seconds? Or have average sex that lasts 10 minutes?",
		"What actor or actress would play you in a movie about your life?",

    ];
})();
